# version: 0.2

# env:
#   variables:
#     IMAGE_TAG: latest
#     ECR_REPO: 203918879825.dkr.ecr.us-east-1.amazonaws.com/dev/fastapi-app
#   privileged: true  # нужно для docker

# phases:
#   pre_build:
#     commands:
#       - REPO_NAME=simple-docker-service-121ef6ee57e1
#       - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 203918879825.dkr.ecr.$AWS_REGION.amazonaws.com
#   build:
#     commands:
#       - docker build -t $REPO_NAME:$IMAGE_TAG .
#       - docker tag $REPO_NAME:$IMAGE_TAG 203918879825.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
#   post_build:
#     commands:
#       - docker push 203918879825.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
#       - echo '{"ImageURI":"203918879825.dkr.ecr.'$AWS_REGION'.amazonaws.com/'$REPO_NAME':'$IMAGE_TAG'"}' > imageDetail.json
# artifacts:
#   files:
#     - '**/*'

version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO: 203918879825.dkr.ecr.us-east-1.amazonaws.com/fastapp-service
    CONTAINER_NAME: fastapi-example
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      # - aws ecs describe-task-definition --task-definition fastapp-service
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $CONTAINER_NAME:$IMAGE_TAG .
      - docker tag $CONTAINER_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' \
          $CONTAINER_NAME $ECR_REPO:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      # - aws ecs update-service --cluster fastapp-cluster-1 --service fastapp-service --force-new-deployment


artifacts:
  files:
    - imagedefinitions.json
