version: 0.2

phases:
  pre_build:
    commands:
      - REPO_NAME=simple-docker-service-121ef6ee57e1
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 203918879825.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG 203918879825.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push 203918879825.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo '{"ImageURI":"203918879825.dkr.ecr.'$AWS_REGION'.amazonaws.com/'$REPO_NAME':'$IMAGE_TAG'"}' > imageDetail.json
artifacts:
  files:
    - imageDetail.json
